### PR TITLE
Allow using an empty 'directory' config entry to mean "use the absolute directory containing the config file."

### PR DESCRIPTION
**Pull request by noahgibbs**
It would be very convenient if a DGD-based application didn't always have to modify the configuration file every time it's installed to a new location (or run an init script that does the same.)

One very common use case for DGD is to put the configuration file into the root directory of the DGD application itself. This patch allows an explicit, empty directory declaration (directory = "") to mean "the directory is the one containing the configuration file." An empty directory entry is currently not usable - it gives a "bad base directory" error when DGD is initialised. So this does not break any currently-working use case.

I'm definitely open to other ways to do this, such as a placeholder variable (e.g. {confdir} or @@confdir@@). But technically I think any change of meaning to an existing filename pattern *could* break some current valid use case. So I chose a value that is currently invalid, and will break no currently-working cases.

Also, the code change for this is quite simple and self-contained.

### CODE REVIEW

**Comment by dworkin** [comment]
This is a bad idea, since a config file within reach of DGD objects allows it to be rewritten by LPC code, creating a huge security problem.

**Comment by noahgibbs** [comment]
All right. Then would you be okay with some other mechanism to specify the relative location of the DGD root and the configuration file?

**Comment by dworkin** [comment]
The simplest way would really be to allow a relative path for 'directory', which is possible as long as it is then converted to an absolute path, using realpath (or _fullpath on Windows).

**Comment by noahgibbs** [comment]
That sounds reasonable to me. Would it be acceptable to you?

**Comment by dworkin** [comment]
Yes, as long as you handle all platforms properly, i.e. use P_realpath, which in host.h is defined as ::realpath on posix systems and _fullpath on Windows.

**Comment by shentino** [comment]
+1 on this, I've often been frustrated myself because I'd rather not mangle the config file every time I rehost the mud into a different folder.  Using a relative path in 'directory' worked at first but then started causing runtime errors.

**Comment by shentino** [comment]
See also https://github.com/dworkin/dgd/issues/32, I'd very much like to see this added to core.  I hope this issue I posted helps with the paperwork on github's end.

**Comment by dworkin** [comment]
I've removed the need for the directory config parameter to be absolute.  Let me know if that solves your problem.

**Comment by shentino** [comment]
So question, does this make directory relative to the location of the config file or relative to the cwd of the command line used to start dgd?

**Comment by shentino** [comment]
Experiment and find out, as usual

Seems that the parameter is interpreted relative to the location from which dgd is invoked.

**Comment by shentino** [comment]
Of note, the test I did was to invoke dgd from within the config file directory itself, and it worked, but cd .. and then executing it specifing the same config file from one level up failed:

shentino@metalhead 2 ~/git $ dgd kotaka/kotaka.dgd
Config error: bad base directory "mud"

**Comment by shentino** [comment]
@noahgibbs I think this is good enough though, you just have to be careful from where you actually invoke dgd, for it to work as you expected you just need to invoke dgd while cwd == same directory as the config file is in

**Comment by noahgibbs** [comment]
This suits our needs, yes. I'll probably put together a small shellscript to invoke it from a dir relative to the config file, but that's very doable.

**Pull request closed without merging**
